name: Deploy to AWS S3
run-name: Deploy to AWS S3 #${{ github.run_number }}
on: [workflow_dispatch]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 bucket
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} --delete
