name: Download Artifact
run-name: ${{ github.actor }} is downloading artifact
on:
  workflow_run:
    workflows: ["Upload Artifact"]
    types: [completed]
    branches: [main, actions/demo]

jobs:
  download_and_print:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts from workflow run
        uses: actions/download-artifact@v4
        with:
          workflow: "Upload Artifact"
          run-id: ${{ github.event.workflow_run.id }}
          path: downloaded-artifacts

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          ls -la downloaded-artifacts/
          echo ""
          echo "Contents of each artifact:"
          for artifact in downloaded-artifacts/*; do
            echo "=== $(basename $artifact) ==="
            if [ -d "$artifact" ]; then
              find "$artifact" -type f | head -20
              echo "..."
            else
              echo "Not a directory"
            fi
            echo ""
          done

      - name: Create summary report
        run: |
          echo "=== ARTIFACT DOWNLOAD SUMMARY ==="
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Triggered by: ${{ github.event.workflow_run.actor.login }}"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Status: ${{ github.event.workflow_run.conclusion }}"
          echo ""
          echo "Artifacts downloaded successfully!"
          echo "Check the logs above for detailed coverage analysis."
